### ISSUE TITLE
Ensure "extent of digitization" is preserved when reading new metadata from Voyager and ASpace 

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#978] opened 2021-01-12 18:29 UTC

**Comment by maxkadel** [comment] 2021-02-04 17:56
Not saving to the database currently, need to add to database, and create and edit views for parent objects

**Comment by maxkadel** [comment] 2021-02-04 17:57
Duplicate of #979  ? Close as duplicate?

**Comment by mikeapp** [comment] 2021-02-04 18:10
looks like it, will close and use other issue.

**Closed by mikeapp** 2021-02-04 18:10 UTC
Labels: software engineering
