### ISSUE TITLE
Migrate LWL collection (PROD portion)

### ISSUE THREAD

**Issue by alisonclemens** [yalelibrary/YUL-DC#1950] opened 2022-03-15 20:32 UTC
**Story**
Following on from #1778

As with the UAT portion of the LWL migration work, we will pull all of the digColl numbers current in Voyager for LWL items, and then use these numbers to extract objects from Fedora. We will migrate these objects only to DCS.

**Acceptance**
- [x] Confirm with Ellen Cordes can reuse list of all digcol numbers from UAT migration in PROD migration
- [x] Import objects into DCS into the LWL admin set
- [x] Fix failed ingests (30 mentioned below by Maggie)
- [x] Make all LWL items public
- [x] Bulk update rights statement field for all objects, to replace what is there with "The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."
- [x] Add mfhds to items (pull these from UAT and batch update)
- [x] Audit objects in DCS with LWL
- [x] Update handles URLs to point to DCS
- [x] Data dump from LB of data for digcolls pulled during migration that will give provide a record of the OIDs; Image file name; Bib; Holdings; Call number; FDID 79 and 74 and Title (FDID 70) to help LWL with post migration cleanup work
- [x] Create reassociation ticket -- #2145

**Background**
Alison's LWL notes and selected files are here: https://yale.box.com/s/bef7hjcs4z2gv6atuuolrj3zx5l1ppzy

**Comment by motropuk** [comment] 2022-04-26 19:45
Have emailed Ellen at LWL to confirm this is the correct list of digcolls we should pull from for the prod migration. Waiting for confirmation [Uploading... LWLfullload_oid_digColl (1).csv]

**Comment by motropuk** [comment] 2022-04-27 16:45
@MaggieZhaoYale we can go ahead an start the migration to PROD now for LWL. We should pull only these digcols https://yale.app.box.com/file/938737137140.

**Comment by MaggieZhaoYale** [comment] 2022-04-28 17:54
19744 records in prod. Failed 30
1. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16715357. This child 15809318 is not in the Fedora. In Fedora, it is a complex parent without children: https://findit.library.yale.edu/catalog/digcoll:2807348. In ladybird, it is the child of 16715357
2. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16711527  the failed children such as 16711853,16711854	,16711855  are inactive 
3. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/17011778 16711854 is inactive
4. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16225993 16226071 is inactive
5. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/17012773 child 17012877 not in Fedora 
6. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16852893 child 15489975 is not in the Fedora. In Fedora, it is a complex parent without children: https://findit.library.yale.edu/catalog/digcoll:2807346. In ladybird, it is the child of 16852893
7. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16852892 child 15481462 (same as 1,6)
8. https://collections.library.yale.edu/management/parent_objects/10931003 simple object, will reprocess it. 
9. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16852894, some inactive children 15490266,15490267, 15490268
10. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16703483/child_objects/16703538 some inactive children, e.g. 16703538
11. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16825828 child 10723231  (same as 1,6,7)
12. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16876283 child 16876284 is not in fedora
13.  10697232 https://collections.library.yale.edu/management/parent_objects/10697232 it is an simple object in fedora, but in ladybird, it has 2 children image
14. https://collections.library.yale.edu/management/batch_processes/8209/parent_objects/16944842  child 16944888 is not in fedora

**Comment by MaggieZhaoYale** [comment] 2022-04-29 18:07
@sshetenhelm Thank you. The children organized into folders by parent objects would be better if it is convenient to you.

**Comment by sshetenhelm** [comment] 2022-04-29 19:18
Sure thing Maggie!

Emailed LWL to ask about some missing images and 'do not publish'/missing metadata in LB.

**Comment by sshetenhelm** [comment] 2022-05-02 17:13
Listing issues using the numbers from @MaggieZhaoYale 's list above:

**Fully Resolved**
Issues 18 and 20 -- All of these children have been marked as "Do Not Publish" and LWL confirmed they can be deleted. These children have been deleted from DCS PROD. They were mistakes that never got deleted from LB.

Issues 16 and 21 -- Confirmed with LWL that the missing child on each of these is either redundant or not actually part of that object and can be deleted. These children have been deleted from DCS PROD.

**In Process**
Issues 1, 4, 6, 7, 8, 10, 11, 12, 14, 19, 22, 23, 24, 25, 26 -- Images for these have been passed on to Maggie

Issue 13 — We have the image files, but we need to create children in DCS for these. 

Issue 2 - There are approximately 212 missing images that I will collect from the LWL server. 

**Outstanding Issues — Dependent on LWL**
Issues 3, 5, 9, and 17 — These files are not on the LWL server. Ellen indicates that they may need to be re-shot. 

Issue 15—
11019111 — Ellen indicated she will need to troubleshoot later
10713236, 10709008, 10713221 — May need to ask for more information for these from Ellen. One has a note "delete" and others are Yale Access Only. Want to verify what should actually be here. 

Issue 15 — 
15960409 — @MaggieZhaoYale Where did this OID come from? I can’t find it in Ladybird for PID 23 or 60

Note: Ellen is on vacation until May 11th, and as such we may not receive some resolutions until after her return.

**Comment by MaggieZhaoYale** [comment] 2022-05-05 17:40
Fixed the following images: https://collections.library.yale.edu/management/batch_processes/8336

**Comment by sshetenhelm** [comment] 2022-05-06 13:54
Waiting on Ellen for re-shoots or info about the following 10 OIDs: 17011778 ; 17012773 ; 16852894 ; 10697232 ; 15815212 ; 11019111 ; 10713236 ; 10709008 ; 10713221 ; 15960409

**Comment by DraxIndustries79** [comment] 2022-05-09 18:10
Ellen Returns:  May 11

**Comment by sshetenhelm** [comment] 2022-05-12 18:00
Parents 17011778 and 17012773 only have PDFs, no master TIFs. Will use .jpd files from LB to try and convert to tif/upload to DCS.

Ellen indicated we can delete the second child of 15815212, as it's just the back of the painting, so they don't have to re-shoot. 

Working through other issues.

**Comment by sshetenhelm** [comment] 2022-05-16 14:14
As per Ellen's request and with approval from Jon, made all LWL items public so LWL can start reviewing.

**Comment by sshetenhelm** [comment] 2022-05-23 17:49
Updated rights for about a quarter of these items. 

For [Batch Process 8738](https://collections.library.yale.edu/management/batch_processes/8738), the job says 'complete' but it only processed 1 out of 9,998 parents. I can't find this process in the Delayed Job Dashboard either. 

For [Batch Process 8739](https://collections.library.yale.edu/management/batch_processes/8739), only 4,790 out of 9,746 parents processed. 

Here's an example from this [Batch Process in the Delayed Job Dashboard](https://collections.library.yale.edu/management/delayed_job_dashboard/show/16244546): 
![Screen Shot 2022-05-23 at 1.48.35 PM.png](https://images.zenhubusercontent.com/61f05050155a1d4a7085c8b9/e04925c6-d4f5-4362-9c4d-b5d2bb2d9dba)

Alicia reported a similar issue in UAT for Garvin.

**Comment by MaggieZhaoYale** [comment] 2022-06-03 18:22
@sshetenhelm https://collections.library.yale.edu/management/parent_objects/10697232 is a complex parents now. Added an extra child for this parent

**Comment by MaggieZhaoYale** [comment] 2022-06-03 19:23
@sshetenhelm Added check list on the issues and checked solved records.
#15 
15960409  does not have ladybird record
11019111, 10713236 , 10713221 do not have title in ladybird

**Comment by sshetenhelm** [comment] 2022-06-09 17:26
@MaggieZhaoYale Sorry! The titles are in the correct field this time.

**Comment by MaggieZhaoYale** [comment] 2022-06-09 17:44
@sshetenhelm Now the metadata is in DCS. I will re-process the images since I deleted the original parents, and new child was created for each simple parent.

**Comment by sshetenhelm** [comment] 2022-06-10 14:03
@MaggieZhaoYale 673 parents have 0 children 
[https://app.zenhub.com/files/242185115/d4c8371d-f0f7-4c76-b0d8-0ecdd3528f73/download](https://app.zenhub.com/files/242185115/d4c8371d-f0f7-4c76-b0d8-0ecdd3528f73/download)

(sorry for .txt file, still can't seem to upload .csv)

**Comment by MaggieZhaoYale** [comment] 2022-06-16 19:51
@sshetenhelm I checked some in the list. These are children of another objects. e.g. 10708912, and 10708913 are the part of 16712271 (not in DCS)
10897594 is part of 10898115 (289  children). We have 10897594 as a child and parent. 
10977794 is part of 16876283 (125 children)We have 10977794 as a child and parent. 
We could delete them as parents.

**Comment by MaggieZhaoYale** [comment] 2022-06-16 21:10
@sshetenhelm Deleted 666 parents in the list. These oids are the children too. 
There are 7 in the list are kept so far:
10708912, 10708913 are the children of  16712271 which is not in the DCS;
15959978,15959979,15960187,15960188,16035079 do not found as children in DCS
Will check these 7 oids.

**Comment by sshetenhelm** [comment] 2022-06-23 16:47
PID 23
Management - 13,952
Blacklight - 13,938

PID 60
Management - 5,128
Blacklight - 5,128

Difference of 14 objects between MGMT and Blacklight. Looking into this.

**Comment by sshetenhelm** [comment] 2022-06-24 20:34
Compared current MGMT PROD list to original digcoll list referenced in #1778 

**Extra OIDs:**
The followings parents in DCS are not from original DigColl/OID list-
15959977, 15960186, 16222773, 16712271

**Not Parents in DCS**
674 parent OIDs are not in DCS. 
- 658 of these were children of other parents in DCS, as per Maggie's prior comment
- 13 are children of parent objects that are not in DCS
- 2 are children of objects that display as simple in FindIt and only have 1 child in DCS, but have multiple children in Ladybird
- 1 was a duplicate that we deleted because the duplicate already exists in DCS

I will speak with LWL about the above issues.

**Comment by MaggieZhaoYale** [comment] 2022-06-29 21:13
Objects with Children:https://collections.library.yale.edu/management/batch_processes/9130

add images to the previous simple objects: https://collections.library.yale.edu/management/batch_processes/9131

**Comment by sshetenhelm** [comment] 2022-06-30 18:00
Handles done! We need to do the LB data dump.

**Comment by sshetenhelm** [comment] 2022-07-05 17:22
[Full LB Data for PID 23](https://yale.box.com/s/x906rkwozyv2lyjiff18wzyq40farknv)

[Full LB Data for PID 60](https://yale.box.com/s/de8myl7dly41o4vj6tvpa9bvska660zh)

Will reconcile with parents in MGMT PROD.

**Comment by sshetenhelm** [comment] 2022-07-05 18:16
Created #2145 for reassociation work. Can close this ticket.

**Closed** 2022-07-05 18:17 UTC
