### ISSUE TITLE
Preservica Parent Sync Issue

### ISSUE THREAD

**Issue by K8Sewell** [yalelibrary/YUL-DC#2638] opened 2023-09-22 15:47 UTC
# Summary
When the structural object id is replaced for a parent object the update process should wipe out all the old childen and replace them with the set on Preservica for the new SO.  Currently, the original children are being kept so this ticket aims to make sure there is a clean slate for the update.

# Screenshot of Current Behavior

![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/2de6b7bf-5846-4301-acc7-3923b36bdf80)

# Acceptance Criteria
- [x] Process to remove child objects that are not in Preservica set works successfully - https://github.com/yalelibrary/yul-dc-management/blob/main/app/models/parent_object.rb#L237
- [x] Create new ticket for cannot allocate memory error message -- #2684 
- [x] Create new ticket for 900979804 tiff error -- #2685

**Comment by martinlovell** [comment] 2023-09-25 18:17
We are checking the checksum as we download the file and raising an error if it doesn't match the value in Preservica:
https://github.com/yalelibrary/yul-dc-management/blob/main/app/models/preservica/bitstream.rb#L31

It may be that the checksum changes even if the tiff doesn't change visually, but it does not seem possible that the checksum changes if the binary data in tiff that we download has not changed.

It may be that some metadata in the tiff changes even when the image data doesn't change. But, I'd be surprised if Preservica updated the files whenever metadata changes.

**Comment by DraxIndustries79** [comment] 2023-09-27 18:06
@sshetenhelm this is to get an email out. :)

**Comment by sshetenhelm** [comment] 2023-09-28 18:07
@sshetenhelm take point on reingesting same files into preservica and pulling in

**Comment by sshetenhelm** [comment] 2023-10-12 17:04
Misunderstood the assignment the first time; as such, I had this object reingested as a new TEST Preservica object.

Successfully connected Preservica info of re-ingested object to current DCS object (OID 900963703). 

Successfully replaced two original children with all 31 new children PLACEHOLDERS. 

HOWEVER, could not pull in images for all children. 

Example image error: 
```
Child Object 900967152 failed to convert PTIFF due to Conversion script exited with error code 1. ---
Script exited with status 1 at line 54
Script exited with status 1 at line 58
---
magick2vips: libMagick error: Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/604
magick2vips: unable to read file "/tmp/d20231012-2940-1twnc4b/900967152.tif"
```

Images failed to ingest for **18 out of 32** child objects.

Pressed ’Synchronize Child Objects’ again

Same, images failed. 

Also looks like there are a bunch of failed SetupMetadata jobs now too for this batch process, for some reason.

**Comment by K8Sewell** [comment] 2023-11-27 15:29
Martin's [PR](https://github.com/yalelibrary/yul-dc-management/pull/1291) should resolve the spawning of extra setup metadata jobs and I believe (will require testing to be sure) this PR will also solve the issue of needing to run a recreate ptiff job after the preservica sync.

Deployed to UAT with release [v2.64.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.64.9)

**Comment by sshetenhelm** [comment] 2023-11-29 18:39
Tried resyncing 900146338 with batch process 1693. Says completed and no error messages, but parent [batch process detail page](https://collections-uat.library.yale.edu/management/batch_processes/1693/parent_objects/900146338) still says “pending” for Processing Queued, Metadata Fetched, and Child Records Created. Is that expected? 

Good news is that I did not spawn a million jobs this time.

**Comment by sshetenhelm** [comment] 2023-11-29 19:07
Parent 900963703, put in Preservica information again, received ["failed to generate PTIFF" errors](https://collections-uat.library.yale.edu/management/delayed_job/failed?queues=ptiff#13288836), cannot read TIFF directory, for multiple children

**Comment by martinlovell** [comment] 2023-11-30 15:48
I checked on of the children: 900979804
I downloaded the access master and was unable to open it on my computer with Preview or Gimp.

I checked the sha 512 checksum of the file and it matched the value in the database on UAT:
```
shasum -a 512 900979804.tif 
daeaaa5e25cb059991223ea93b244aee409744cc54ee6cddf304b17264fda12260656bb66a455ebb47a9db0beb64b3a831f9a9d5617e34d2cc38854542c98eb3  900979804.tif
```

So, assuming the checksum value in the db is the value we got from Preservica, we have the right data from Preservica since the checksums match, but something is wrong with the tiff in Preservica.

**Comment by sshetenhelm** [comment] 2023-12-01 18:58
SO - 

I tried a new sync, and I can confirm that the original children DID successfully get removed. However, I got [the following error message](https://collections-uat.library.yale.edu/management/batch_processes/1698/parent_objects/901602583): 

![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/234404a9-8a15-4afc-9452-6c8dd0145a05)

Any clue what that means? I put in the wrong UUID maybe?

**Comment by sshetenhelm** [comment] 2023-12-01 19:44
THANK YOU @K8Sewell and @martinlovell. Created tickets for two other issues, closing this one. I appreciate all the hard work you've both put into this--I know it was a pain!!!

**Closed** 2023-12-01 19:44 UTC
