### ISSUE TITLE
Voyager field statistics

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#304] opened 2020-06-30 16:17 UTC
**STORY**
As a product owner, I want to understand which fields occur with what frequency in LadyBird.

**ACCEPTANCE**
Using a random sampling of 10,000 public items from Voyage (i.e. the Voyager endpoint in the Metadata Cloud)
- [ ] Produce a list of which field names occur
- [ ] Count how many times each field occurs (this should be a number somewhere between 1 and 10,000)
    - [ ] Display the raw count
    - [ ] Display the count as a percentage of the total sample

**IMPLEMENTATION NOTE**
We may want to re-run this with different sample sets and sizes over the duration of the project, so provide a mechanism to run this as a rake task or page we can display in the management web app.

**Comment by maxkadel** [comment] 2020-07-20 21:05
This is a duplicate of #305

**Closed** 2020-12-15 05:24 UTC
Labels: duplicate
