### ISSUE TITLE
Advanced Search page should have a link/button back to basic search

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#593] opened 2020-09-19 20:18 UTC
**ACCEPTANCE**
- [x] The "Start Over" button does not appear at the top of the Advanced Search page
- [x] There is a clear clickable target that takes me back to basic search from the homepage

![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/6e77201b-0130-4bc8-b547-b64b42a38b62)

**Comment by DraxIndustries79** [comment] 2020-09-22 17:16
We need some clarity on this

**Comment by DraxIndustries79** [comment] 2020-09-29 18:04
Duplicate of https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/561?

**Comment by mark-dce** [comment] 2020-10-06 17:00
Completed as part of the Advanced search body ticket?

**Closed** 2020-10-06 17:08 UTC
Labels: Software Engineering, discovery team
