### ISSUE TITLE
Investigation: Health Status of Test Environment

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#1788] opened 2021-12-01 18:50 UTC
**User Story** 
As the product owner, I want the test environment in a healthy state.  

**Acceptance Criteria**
- [x] read the [log]([https://app.zenhub.com/files/242185115/e3c14514-eb44-4a29-ba89-d6221e6e1454/download](https://app.zenhub.com/files/242185115/e3c14514-eb44-4a29-ba89-d6221e6e1454/download)url) 
- [x] investigate the issue of the unhealthy state
- [x] discuss a plan to fix and remediate the heath state

**Possible Hint:**
     The other environments are healthy.  

**Error from the log:** 
               [Office365connector] Matched status 'FAILURE' for webhook with name 'jenkins-notification'.
               Finished: FAILURE

**Comment by bobrice** [comment] 2021-12-03 18:30
I don't think the 0365 webhook is the cause of the failures.  I've removed it from the job and kicked it off again.

**Comment by bobrice** [comment] 2021-12-03 18:36
Added the notifiction webhook back since it wasn't the problem.

**Comment by bobrice** [comment] 2021-12-03 18:37
This error seems more like a problem....

rspec ./smoke_spec/deploy_spec.rb:107 # The cluster at https://yul-dc:nocrawl@collections-test.library.yale.edu The manifest service at https://yul-dc:nocrawl@collections-test.library.yale.edu provides a manifest for item 16371253:  has a sequence with six canvases that links an image to a live URI

**Comment by mikeapp** [comment] 2021-12-03 18:53
I updated the object 16371253 so it has a IIIF v3 Manifest.

#1790 changes the smoke test to expect a IIIF v3 Manifest, but the objects it tests also need to be updated via the Management UI.

**Comment by mikeapp** [comment] 2021-12-03 18:56
I've updated both 2005512 and 16371253 in UAT, so they have the new v3 Manifest format

**Comment by bobrice** [comment] 2021-12-03 18:57
Not sure what this is expecting, but ...."expect(parsed_manifest['items'].length).to eq(6)"

Error seems to be related though...
NoMethodError:
       undefined method `length' for nil:NilClass

**Comment by mlooney** [comment] 2021-12-03 19:07
oh, I was thinking this was about the failure to read the ecs yml config file, but appears to be the smoke test thing?

@bobrice that error indicates that parsed_manifest object did not contain a key named "items", fwiw

**Comment by mikeapp** [comment] 2021-12-03 19:08
I think there were some failures due to other issues.

**Comment by bobrice** [comment] 2021-12-03 19:19
Looks like you fixed this one.  Seems like it can be closed.

**Comment by mlooney** [comment] 2021-12-03 19:23
@mikeapp bob was able to successfully deploy, so I think this can be closed.

**Comment by mikeapp** [comment] 2021-12-03 19:29
Thanks!  For the record, I have updated the objects used by the IIIF parts of smoke test on staging and production as well.  (I'm assuming the Camerata change that was merged yesterday will be in effect across all deployments.)

**Closed by mikeapp** 2021-12-03 19:29 UTC
Labels: software engineering, dev-ops
