### ISSUE TITLE
SPIKE: Use Environment Variables to select environment for Blacklight server

### ISSUE THREAD

**Issue by edejesusyale** [yalelibrary/YUL-DC#405] opened 2020-08-03 16:01 UTC
SPIKE

### Story: 
As a developer, I want to use the development environment for writing code. As of now, changes to any file that is not a `*.html` requires us to reset the container and consumes time because the server runs in Production. There needs to be an intuitive and simple way to select which environment the blacklight server is ran in.

### ACCEPTANCE:
- [ ] There is a way of setting which environment is used in the .env for the blacklight container

**Comment by orangewolf** [comment] 2020-08-14 17:14
No update from yesterday, was working with max and then JP/Dylan. I’ll hit this fresh Monday

**Comment by orangewolf** [comment] 2020-08-21 05:40
I've confirmed that this is something in our code - it does happen when you run the app outside of Docker. It does still happen after upgrading to Blacklight 7.10.0. It does not happen on a fresh Blacklight 7.10.0 app.

**Comment by orangewolf** [comment] 2020-08-25 17:29
@edejesusyale @FCRodriguez7 because this is a chore - if you can validate that it is working for you in master now, you can close this ticket.

**Comment by FCRodriguez7** [comment] 2020-08-27 20:50
This is not working.  I’ve confirmed it today.

**Comment by FCRodriguez7** [comment] 2020-08-28 17:40
We, Rob and I, confirmed that this is working.

**Closed by FCRodriguez7** 2020-08-28 17:40 UTC
Labels: Chore, bug, discovery team, management team
