### ISSUE TITLE
OwP: Notify user if they have a pending request for a parent

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2657] opened 2023-10-04 20:48 UTC
**Story**

If the user navigates to an OwP item for which they have a pending request, Blacklight should display this fact.

_Your request to access this item has been received. Thank you for your patience as we consider your request. You will be notified of the results of your request once a decision has been made._

**Acceptance**
- [x] Instead of showing the link to the request form, display the message: _Your request to access this item has been received. Thank you for your patience as we consider your request. You will be notified of the results of your request once a decision has been made._
- [x] Since the user does not have permission, they should not have access to the digital content, text, etc.

**Comment by jpengst** [comment] 2024-01-04 17:31
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/952

**Comment by jpengst** [comment] 2024-01-09 18:26
Looks good on Demo:  


![Image](https://github.com/yalelibrary/YUL-DC/assets/24666568/89a7dc01-6a61-448e-903a-97745d71bbf3)

**Comment by sshetenhelm** [comment] 2024-01-17 16:42
Submitted ticket via ServiceNow to address collections-demo display issues.

**Comment by sshetenhelm** [comment] 2024-01-18 18:20
This is what I see, even when logged in (browser saved my credentials from last time): 


![Image](https://github.com/yalelibrary/YUL-DC/assets/98423494/c38d0bc0-a5c5-44a7-ae84-b0ed4bacc41b)

**Comment by sshetenhelm** [comment] 2024-01-18 18:29
Updates: 
* Error ONLY shows for Open with Permission parents.
*  All Open with Permission parents in Management App have broken image icons for their representative thumbnails, and child objects have broken image icon (Chrome, regular and incognito browsers; also Firefox)
* Running 'Regenerate child OID ptiff' process appeared to complete, but did not regenerate thumbnails in Management
* Changing status to 'Yale Community Only' allowed thumbnails to show, and parent object page to display in Blacklight

**Comment by K8Sewell** [comment] 2024-02-27 17:50
I'm not positive but this is working for me on Demo so it may be ready for retesting on Demo.  Search for owp objects did not seem broken either but absolutely worth double checking.



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/9cf1c201-4b3a-414c-a6a1-455bf2233d2d)



![Image](https://github.com/yalelibrary/YUL-DC/assets/36549923/b1bcd975-29c3-4b74-95f9-f1dc5073313c)

**Comment by sshetenhelm** [comment] 2024-02-27 18:31
1. I was able to search for two Open with Permission objects.
2. I successfully received the "pending requests" message.

The only thing I was not able to test was the Full Text Status, because nothing in DEMO has full text attached, and there is currently no way for me to attach full text.

**Comment by DraxIndustries79** [comment] 2024-02-27 19:05
- [ ] Check for PDFs at bottom of page.
- [ ] Create ticket for full text.
- [ ] Close this.l

**Comment by sshetenhelm** [comment] 2024-02-28 15:36
- Confirmed that PDFs, Mirador, and Manifest links are turned off
- Confirmed that I get "unauthorized" error when trying to directly navigate to IIIF manifest and PDF urls, and just a blank screen for the Mirador url (with nothing of note in the "View Source" view except the manifest URL). 
- Created #2752 for testing Full Text

**Closed** 2024-02-28 19:03 UTC
Labels: feature branch
