### ISSUE TITLE
Update Metadata Cloud Mappings for newest version of MC API

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#756] opened 2020-10-30 17:56 UTC
**STORY**
I would like to see the latest format of metadata provided by the metadata cloud displayed in the discovery application, so that 

**ACCEPTANCE**
- [ ] ???

**Comment by dl-maura** [comment] 2020-12-01 19:06
dupe of 683

**Closed** 2020-12-01 19:27 UTC
Labels: duplicate, software engineering
