### ISSUE TITLE
Bug "Sort By Relevance" & "10 PER PAGE"

### ISSUE THREAD

**Issue by FCRodriguez7** [yalelibrary/YUL-DC#566] opened 2020-09-11 21:13 UTC
[Uploading... Screen Recording 2020-09-11 at 05.09.59 PM.gif ]

**Comment by FCRodriguez7** [comment] 2020-09-11 21:14
![Screen Recording 2020-09-11 at 05.09.59 PM.gif](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b7fe2285-fba7-479f-8a16-1e9f8c9a5279)

**Comment by alishaevn** [comment] 2020-09-17 15:10
Duplicate of #564

**Comment by FCRodriguez7** [comment] 2020-09-18 16:18
Dup: https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/564

**Closed** 2020-09-18 16:18 UTC
Labels: bug, discovery team, duplicate
