### ISSUE TITLE
Nightly Job - Integrity Check

### ISSUE THREAD

**Issue by sshetenhelm** [yalelibrary/YUL-DC#2855] opened 2024-06-10 14:00 UTC
**Story**
We would like to ensure the integrity of files that were migrated into DCS from FindIt. To do so, we would like to create a nightly job that would check the integrity of the files.

For the job, we would like to check a random sample of **2000** child object files to validate that they still exist on disk, to calculate the checksums, etc. 

The child objects should be attached to any parent that **does not have** a Digital Object Source of Preservica.

**Acceptance**

- [x] Nightly job created to check child image file integrity, file presence, then checksum
- [x] Nightly job checks full number of children specified
- [x] Make a ticket for how to deliver results - #2867

**Comment by K8Sewell** [comment] 2024-07-08 21:10
PR ready for review - https://github.com/yalelibrary/yul-dc-management/pull/1411

**Comment by jpengst** [comment] 2024-07-15 22:55
Deployed to test v2.70.8

**Comment by sshetenhelm** [comment] 2024-07-16 13:46
```2024-07-16 00:15:02 UTC | Failed | Integrity Check incomplete because of error: undefined method `parent_object' for nil:NilClass```
https://collections-test.library.yale.edu/management/batch_processes/874

**Comment by K8Sewell** [comment] 2024-07-17 18:37
Deployed to Test with release [v2.70.9](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.70.9)

**Comment by K8Sewell** [comment] 2024-07-17 21:06
Investigating not null error for connectable_id.  Taking it back to in progress.



![Image](https://github.com/user-attachments/assets/eb8fd4f8-b118-49bb-808b-ce52f69a26a7)

**Comment by K8Sewell** [comment] 2024-07-18 16:49
Should we expect to find parent objects on UAT or PROD that are similar to this [parent object](https://collections-test.library.yale.edu/management/parent_objects/1633987014242)?  It has a child object count of 1, has a child object listed on the show page, but the link for that child goes to the child object datatable.  If yes, then we can add some more guards in the code.  Currently deploying this to another env to see if the job completes successfully on Demo.

**Comment by sshetenhelm** [comment] 2024-07-18 17:04
We would expect parent objects with attached child objects that have no images, but in theory that link should go to the individual child OID page, not the data table. That's from an older failed ingest though (2021-10-12 12:58:55 UTC) so maybe that is why it is wonky.

I will look at a few other older objects and check the behavior.

**Comment by jpengst** [comment] 2024-07-18 17:29
Confirmed that the integrity check is working on demo (https://collections-demo.library.yale.edu/management/batch_processes/154) and failed on test due to bad parent/child data.

**Comment by sshetenhelm** [comment] 2024-07-19 17:31
Confirmed I see two Integrity Check jobs on UAT, both of which completed successfully and provides information for 2000 child objects.

I'm assuming it's working although I'm not sure how we would... like... test to make sure it actually alerted us if it found a child lacking integrity, if that makes sense?

**Comment by jpengst** [comment] 2024-07-19 17:53
Taking back to in progress.  
Yeah that makes sense, Summer. It looks like most of those child objects failed its checksum comparison and there's no indication that it failed unless you click on the parent object oid and look to see if it passed/failed.  

It also looks like the checksum is not being saved on the child objects. The failure message is not showing any checksum saved to the child object its comparing against so basically all of them are failing except for a couple.

**Comment by jpengst** [comment] 2024-07-22 16:57
- [ ] Alter job to check for file presence instead of comparison

**Comment by K8Sewell** [comment] 2024-07-23 15:16
PR merged - https://github.com/yalelibrary/yul-dc-management/pull/1416

**Comment by K8Sewell** [comment] 2024-07-23 15:40
Deployed to Test with release [v2.71.0](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.0)

**Comment by K8Sewell** [comment] 2024-07-23 16:01
Check only assesses file presence.  Will promote to UAT.



![Image](https://github.com/user-attachments/assets/b10051cf-2188-4c87-be1b-311f21095fee)

**Comment by jpengst** [comment] 2024-07-23 17:20
Show failed parents PR: https://github.com/yalelibrary/yul-dc-management/pull/1417

**Comment by K8Sewell** [comment] 2024-07-23 18:35
Deployed to Test with release [v2.71.1](https://github.com/yalelibrary/yul-dc-management/releases/tag/v2.71.1)

**Comment by K8Sewell** [comment] 2024-07-23 20:39
Shows expected status on parent objects on batch detail page.  Will promote to UAT.



![Image](https://github.com/user-attachments/assets/d5a0d31a-80ba-4a76-b2c0-30618ee486b7)

**Comment by laurenb33** [comment] 2024-07-24 17:38
Lookin' good on UAT! 

![Image](https://github.com/user-attachments/assets/992c6c10-3695-42cf-8b8c-4a76d5717c86)

**Closed** 2024-07-24 18:03 UTC
