### ISSUE TITLE
Update Yale Fonts

### ISSUE THREAD

**Issue by DraxIndustries79** [yalelibrary/YUL-DC#1263] opened 2021-05-04 18:52 UTC
**Story**

Apply the Yale fonts in the Management interface using fonts from the static site that was set up for the project

**Acceptance**

- [ ] Confirm fonts exist via Inspector.  (Actual implementation of fonts will come in a later ticket)

**Comment by alishaevn** [comment] 2021-05-04 18:54
# Previous PR's related to fonts:
- https://github.com/yalelibrary/yul-dc-blacklight/pull/325
- https://github.com/yalelibrary/yul-dc-blacklight/pull/405
- https://github.com/yalelibrary/yul-dc-blacklight/pull/455
- https://github.com/yalelibrary/yul-dc-blacklight/pull/459

**Comment by alishaevn** [comment] 2021-05-05 02:35
co-author: alisha evans <alisha@notch8.com>
co-author: dylan salay <dylan@notch8.com>

# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/1263

# Expected behavior
- this PR added the yale font families to the management repo as variables
- it did not use the yale font family variables

**Comment by alishaevn** [comment] 2021-05-05 02:37
Moved the ticket back to in sprint because although the PR that added the yale fonts was merged, the design implementation for the fonts hasn't been decided yet.

**Closed** 2021-05-07 20:06 UTC
