### ISSUE TITLE
Remove Subject Topic SSIM from Item Page Metadata (and anywhere else it shows in the UI) (Bugherd)

### ISSUE THREAD

**Issue by dl-maura** [yalelibrary/YUL-DC#609] opened 2020-09-22 18:12 UTC
From Bugherd: https://www.bugherd.com/t/QpmKbMvBn6KhpiHJr3odVw

We have Subject Topic and then Subject Topic Ssim, we don't need Subject Topic SSIM to display on this page, just Subject Topic

**Comment by mikeapp** [comment] 2020-09-22 18:14
Duplicate of #578 ?

**Comment by dl-maura** [comment] 2020-09-23 15:12
@mikeapp looks like it!

also not sure if this is being indexed and therefore would sometimes show if it is a highlight match

**Closed** 2020-09-29 17:50 UTC
Labels: discovery team, duplicate
