### ISSUE TITLE
Paginate BatchProcess index page

### ISSUE THREAD

**Issue by martinlovell** [yalelibrary/YUL-DC#664] opened 2020-10-08 16:49 UTC
The list of BatchProcesses will get big quick, so it needs to be paginated.  (datatables)

**Comment by dl-maura** [comment] 2020-10-12 15:39
Dupe of #671?

**Comment by mark-dce** [comment] 2020-10-13 15:51
Good call - I had it too and wrote a slightly more detailed ticket.

Superseded by #671

**Closed by mark-dce** 2020-10-13 15:51 UTC
Labels: duplicate, software engineering
